@include('layouts.header')
<div class="container">
    <div class="row">
        <div class="col-sm-8">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nobis facilis quas modi officiis delectus eveniet, possimus, dignissimos, repellendus nostrum nam labore ab unde excepturi aspernatur aliquid inventore deleniti minima ratione. Atque odit earum ex. Magni neque optio, provident eveniet ratione totam. Quis nihil optio suscipit at, tempore minima hic fugiat ea, ullam cum laboriosam nam velit odit animi aliquid inventore quae incidunt reprehenderit voluptate veritatis recusandae asperiores ut assumenda? Voluptatum, officiis debitis eveniet ab suscipit quod impedit labore? Unde corporis quis voluptatibus maiores eaque, ea, dolores optio quam ex libero itaque at voluptas quae soluta laudantium sint quia sapiente alias maxime qui officia. Aliquam quia aliquid ab soluta sint officiis dignissimos, quis officia provident culpa. Numquam aut rem unde dicta delectus eius, natus corrupti aliquid. Aliquam nam vel velit quaerat quasi! Ad quisquam facilis vel cupiditate corrupti doloremque nostrum velit error, odio blanditiis magni hic exercitationem quasi adipisci nihil similique, necessitatibus iure asperiores nam molestiae animi aut! Doloribus voluptates sequi fugit alias placeat dolorem tempore animi debitis eaque rem, aliquam, optio soluta. Facere, assumenda eveniet omnis beatae eaque laboriosam asperiores molestias quam impedit iusto sint ipsam fugit cumque hic ducimus numquam et rerum nihil nostrum? Qui dignissimos doloribus vero assumenda dolores earum ut, repellat eaque architecto hic quis sapiente quisquam libero ipsum eligendi, iure autem nobis inventore expedita fuga accusamus quos error! Non blanditiis est minus, quis nulla explicabo. Dolorem delectus hic, voluptatum eius modi et corporis praesentium quisquam facilis ad ut optio mollitia aperiam harum molestias aut facere saepe officia nemo esse. Maiores fuga quod itaque, ab hic perspiciatis accusantium dignissimos rerum quibusdam quia vel incidunt delectus officia magni aspernatur temporibus eaque a recusandae sapiente voluptate facilis dolor. In placeat animi, autem omnis ducimus, exercitationem qui accusamus quis vero perspiciatis voluptate at commodi. Quam adipisci similique amet numquam minima est quisquam, consequuntur ea rem enim exercitationem delectus praesentium accusantium assumenda eum, dolorem, saepe nulla vero eius iste illum! Autem amet commodi, explicabo itaque nulla, ut accusamus recusandae blanditiis eos facilis placeat porro aspernatur, pariatur molestias nostrum natus necessitatibus sed provident dolorem praesentium? Nostrum dolore reprehenderit placeat omnis. Cupiditate, amet impedit. Ducimus, inventore fuga consequuntur asperiores, earum officiis porro molestias nobis, error tenetur sapiente exercitationem quam itaque dolorum nesciunt repellat mollitia? Odit enim impedit ipsum nihil corrupti. Doloremque, quibusdam deleniti non rerum atque odit expedita fugiat nobis, beatae recusandae sint quae? Ipsum quae earum ea nulla pariatur quidem dolor quos!
            {{-- @yield('main-content') --}}
        </div>
        <div class="col-sm-4">
Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa eveniet consectetur minima tempora adipisci iure alias neque excepturi earum maiores numquam id sunt odio, deserunt quisquam iste dicta magni rerum saepe architecto nam amet voluptates! Laudantium fugit corporis harum, natus dolores, optio quaerat reprehenderit iste in voluptatibus minima assumenda. Illum officiis, non fugiat iste illo ullam minus vero omnis? Voluptates?
        </div>
    </div>
</div>
@include('layouts.footer')
